#!/usr/bin/env python3
"""Generate website license pages from deps.json + versions.env.

Reads docs/deps/deps.json and linux/scripts/01-core/versions.env (same sources
as third-party-licenses.md) and produces the Flutter asset markdown files that
get rendered at /openSourceLicenses on the website.

Usage:
    python external/Kataglyphis-DocumANTation/docs-tooling/scripts/generate-website-licenses.py --check   # verify files are current
    python external/Kataglyphis-DocumANTation/docs-tooling/scripts/generate-website-licenses.py --write   # regenerate files
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Paths default to the conventional ContainerHub layout but are configured at
# runtime from CLI arguments (see configure_paths / main) so this generator can
# run against any consuming repository from the shared docs-tooling submodule.
REPO_ROOT = Path.cwd()
DEPS_JSON = REPO_ROOT / "docs/deps/deps.json"
VERSIONS_ENV = REPO_ROOT / "linux/scripts/01-core/versions.env"
ASSETS_DIR = REPO_ROOT / "linux/webserver/dist/assets/assets/documents/footer"


def configure_paths(
    repo_root: Path,
    deps_json: Path | None,
    versions_env: Path | None,
    assets_dir: Path | None,
) -> None:
    """Point the module-level path globals at the consuming repository."""
    global REPO_ROOT, DEPS_JSON, VERSIONS_ENV, ASSETS_DIR
    REPO_ROOT = repo_root.resolve()
    DEPS_JSON = deps_json.resolve() if deps_json is not None else REPO_ROOT / "docs/deps/deps.json"
    VERSIONS_ENV = (
        versions_env.resolve()
        if versions_env is not None
        else REPO_ROOT / "linux/scripts/01-core/versions.env"
    )
    ASSETS_DIR = (
        assets_dir.resolve()
        if assets_dir is not None
        else REPO_ROOT / "linux/webserver/dist/assets/assets/documents/footer"
    )


EN_TEMPLATE = """# Open Source Licenses

This project's container images bundle several open-source and proprietary
software components.  This page lists the major components, their versions,
repositories, and licenses.

The project's own code is licensed under MIT.  Each upstream component carries
its own license terms.

---

{container_table}

---

## Flutter Web Frontend

The web frontend uses the Flutter SDK and several Dart/Flutter packages.
Their full license texts are bundled in the application at
`/assets/NOTICES` (auto-generated by the Flutter build).
"""

DE_TEMPLATE = """# Open-Source-Lizenzen

Die Container-Images dieses Projekts enthalten mehrere Open-Source- und
proprietäre Softwarekomponenten. Diese Seite listet die wichtigsten
Komponenten, ihre Versionen, Quellen und Lizenzen auf.

Der eigene Code des Projekts steht unter der MIT-Lizenz. Für jede
vorgelagerte Komponente gelten die jeweiligen Lizenzbedingungen.

---

{container_table}

---

## Flutter Web Frontend

Das Web-Frontend verwendet das Flutter SDK und mehrere Dart/Flutter-Pakete.
Die vollständigen Lizenztexte sind in der Anwendung unter
`/assets/NOTICES` gebündelt (automatisch vom Flutter-Build generiert).
"""


def parse_versions_env() -> dict[str, str]:
    result: dict[str, str] = {}
    for line in VERSIONS_ENV.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        result[key.strip()] = value.strip()
    return result


def resolve_version(entry: dict, versions: dict[str, str]) -> str:
    var = entry.get("var")
    if var and var in versions:
        return versions[var]
    fixed = entry.get("version_fixed")
    if fixed:
        return fixed
    return "—"


def render_table(versions: dict[str, str]) -> str:
    metadata = json.loads(DEPS_JSON.read_text(encoding="utf-8"))
    lines: list[str] = []

    for section in metadata["sections"]:
        title = section["title"]
        tag = section.get("tag", "")
        heading = f"## {title}"
        if tag:
            heading += f" (`{tag}`)"
        lines.append("")
        lines.append(heading)
        lines.append("")

        for subsection in section["subsections"]:
            subtitle = subsection["title"]
            df = subsection.get("dockerfile", "")
            sub_heading = f"### {subtitle}"
            if df:
                sub_heading += f" (`{df}`)"
            lines.append(sub_heading)
            lines.append("")
            lines.append("| Software | Version | Repository | License |")
            lines.append("| --- | --- | --- | --- |")

            for entry in subsection["entries"]:
                name = entry["name"]
                ver = resolve_version(entry, versions)
                url = entry.get("url", "")
                lic = entry.get("license", "")
                if url:
                    display = url.replace("https://", "").replace("http://", "").rstrip("/")
                    repo = f"[{display}]({url})"
                else:
                    repo = "—"
                lines.append(f"| {name} | {ver} | {repo} | {lic} |")
            lines.append("")

    return "\n".join(lines)


def generate_content(versions: dict[str, str]) -> tuple[str, str]:
    table = render_table(versions)
    return (
        EN_TEMPLATE.format(container_table=table),
        DE_TEMPLATE.format(container_table=table),
    )


def write_files(en_content: str, de_content: str) -> list[Path]:
    en_path = ASSETS_DIR / "openSourceLicensesEn.md"
    de_path = ASSETS_DIR / "openSourceLicensesDe.md"
    en_path.parent.mkdir(parents=True, exist_ok=True)
    de_path.parent.mkdir(parents=True, exist_ok=True)
    en_path.write_text(en_content, encoding="utf-8")
    de_path.write_text(de_content, encoding="utf-8")
    return [en_path, de_path]


def check_current(en_content: str, de_content: str) -> bool:
    en_path = ASSETS_DIR / "openSourceLicensesEn.md"
    de_path = ASSETS_DIR / "openSourceLicensesDe.md"
    return (
        en_path.exists()
        and en_path.read_text(encoding="utf-8") == en_content
        and de_path.exists()
        and de_path.read_text(encoding="utf-8") == de_content
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate website license pages.")
    parser.add_argument("--check", action="store_true", help="Fail if files are out of date.")
    parser.add_argument("--write", action="store_true", help="Regenerate files in place.")
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path.cwd(),
        help="Root of the consuming repository (default: current directory).",
    )
    parser.add_argument(
        "--deps-json",
        type=Path,
        default=None,
        help="Path to deps.json (default: <repo-root>/docs/deps/deps.json).",
    )
    parser.add_argument(
        "--versions-env",
        type=Path,
        default=None,
        help="Path to versions.env (default: <repo-root>/linux/scripts/01-core/versions.env).",
    )
    parser.add_argument(
        "--assets-dir",
        type=Path,
        default=None,
        help=(
            "Directory to write the generated license markdown into "
            "(default: <repo-root>/linux/webserver/dist/assets/assets/documents/footer)."
        ),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    configure_paths(args.repo_root, args.deps_json, args.versions_env, args.assets_dir)

    if not DEPS_JSON.exists():
        print(f"Error: {DEPS_JSON} not found", file=sys.stderr)
        return 1
    if not VERSIONS_ENV.exists():
        print(f"Error: {VERSIONS_ENV} not found", file=sys.stderr)
        return 1

    versions = parse_versions_env()
    en_content, de_content = generate_content(versions)

    if args.check:
        if check_current(en_content, de_content):
            print("Website license files are up to date.")
            return 0
        print("Website license files are out of date.", file=sys.stderr)
        print(
            "Run: python external/Kataglyphis-DocumANTation/docs-tooling/scripts/generate-website-licenses.py --write",
            file=sys.stderr,
        )
        return 1

    paths = write_files(en_content, de_content)
    for p in paths:
        try:
            shown = p.relative_to(REPO_ROOT)
        except ValueError:
            shown = p
        print(f"Written: {shown}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
